TEXT_EXTENSIONS = {".txt", ".md", ".markdown"}
OFFICE_EXTENSIONS = {".docx", ".pptx", ".xlsx", ".csv"}
IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".gif"}
KNOWLEDGE_FILE_EXTENSIONS = {".pdf", *TEXT_EXTENSIONS, *OFFICE_EXTENSIONS, *IMAGE_EXTENSIONS}
CHAT_FILE_EXTENSIONS = KNOWLEDGE_FILE_EXTENSIONS
MAX_CHUNK_CONTENT_CHARS = 12000
